### ISSUE TITLE
UX: Menu State Indication

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/whale_map#1]
For the Menu top right corner: 

**? -> Mouse or Touch: no indication of which of the two options is chosen.**

When the question mark is chosen, the user is offered two options: Mouse or Touch. There is no indication on which is the current selection. The parent menu however works with status indications (which is good). This adds an extra step for the user to figure out at the first time what that Mouse Touch text is under the menu. The problem is enforced by the text alignment. It appears as if the text belongs to both "Mouse" and "Touch". See red square indication in screenshot. 

![whale01](https://cloud.githubusercontent.com/assets/26263513/23685508/58d79c74-0409-11e7-9afb-5fc083813338.jpg)

**Comment by neon-ninja** [comment]
The currently selected tab is a lighter shade of gray than the other tab. Perhaps the tabs could have some more visual cues similar to bootstrap tabs http://getbootstrap.com/javascript/#tabs

**Comment by DorisAtCeR** [comment]
Yes, it needs to be more obvious. Depending on screen colours and eye sight
this is unnoticed. Can you make it the same style as the menu hierarchy
level above, i.e. have an yellow/orange frame?

**Comment by neon-ninja** [comment]
Take a look at https://uoa-eresearch.github.io/whale_map/ - I've done as you've suggested, in commit https://github.com/UoA-eResearch/whale_map/commit/4b7f68f817d76204c75e09c689d08d894cfbd949

**Comment by DorisAtCeR** [comment]
Yea, it's more understandable now. The text still goes into the space of the other option and the frame is thicker than those at a menu level above but yea that would be the idea. I also noticed that for the map style the frame is actually green rather than orange.
