### ISSUE TITLE
UX: Compass

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/whale_map#10]
Why would you not show the entire compass? There appears to be room. But it might only my personal preference. It looks a bit squashed to me.

**Comment by neon-ninja** [comment]
This is a speed control, not a compass

**Comment by DorisAtCeR** [comment]
Yea ok, as said in other issue number, I would change this to a slider with a mouse over and possibly a label. Or you could say "55x of real time" or "55 times time lapse" instead of "55x" or something like that.
