### ISSUE TITLE
UX: unclear number

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/whale_map#2]
Menu in compass bottom left corner:

What does the number that is followed by an 'x' (above the date in the compass) mean? For example 124560x. Some indication of the meaning would be helpful.

**Comment by neon-ninja** [comment]
It's a factor that means how much faster than real time the simulation is running. So, in the example given, the simulation is running 124560 faster than real time. Perhaps some mouseover text explaining this number would be helpful

**Comment by DorisAtCeR** [comment]
Yes, and additionally even a label such as "Time Lapse"

**Comment by neon-ninja** [comment]
https://github.com/UoA-eResearch/whale_map/commit/85c8f83ba3b4e0a2c4fc8c14f2ca20eb9f4a468b should resolve this issue
