### ISSUE TITLE
UX: Meaning of Whale Colour

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/whale_map#3]
It appears to me that the colour of the whales indicates a pod of whales. Is this assumption correct? If this is incorrect and each whale is an independent individual try to assign a distinct colour. If it does symbolize a pod an explanation would be good, I would probably expect that under '?' like a FAQ.

**Comment by neon-ninja** [comment]
Each whale is an individual. Pink = female, blue = male, green = DNA tests inconclusive. I agree a legend would be a good idea

**Comment by DorisAtCeR** [comment]
:-)
