### ISSUE TITLE
UX: Compass Function

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/whale_map#6]
What is the function of the compass? I can see that the numbers change, to for example 150x, but I can neither see the visualization change nor understand the meaning.

**Comment by neon-ninja** [comment]
This changes the progression of time. See https://github.com/UoA-eResearch/whale_map/issues/2. Perhaps mouseover text on the green arrow would also be helpful

**Comment by DorisAtCeR** [comment]
I would seriously contemplate making it a slider + mouse over. The current control very much resembles a compass. In the context of a globe this impression is enforced even further. I thought it is supposed to change the orientation of the globe and the number was some sort of geographical location data - and that it was broken.

A slider is perfect for the change of this single value.
