### ISSUE TITLE
UX: Clock Symbol

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/whale_map#7]
The clock symbol next to the compass seems to be doing nothing. What is its function?

**Comment by neon-ninja** [comment]
This sets the simulation time to the current time. It is disabled for this visualisation as the data is in the past

**Comment by DorisAtCeR** [comment]
Well, it uses grey levels that exist in the active "compass". So visually the user gets no clue that it is inactive. It also overlaps with the "compass" that gives that area of your page a random look as if you forgot to place it properly. The user has no possibility of figuring out what it is. I thought it might be a broken control that toggles between the 24h system and AM/PM.
