### ISSUE TITLE
UX: Toggle Day/Night Cycle

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/whale_map#9]
Switching on the toggle day/night cycle visualization causes a somewhat nauseating effect at the speed the visualization runs. What is the purpose? Is there a slow motion feature that would make a day/night feature more useful? Then one could for example see if the whales travel at night or during the day.

**Comment by neon-ninja** [comment]
It's a visual indicator that provides a temporal frame of reference - so the user doesn't need to keep referring to the clock in the bottom left. Yes - if you slow the simulation using the green arrow, the day/night cycle progresses less rapidly.

**Comment by DorisAtCeR** [comment]
Yes, if the time lapse control is changed this feature should become more understandable and usable.
